name: VoidFightZ
version: '1.0-SNAPSHOT'
main: me.in4.voidfightz.VoidFightZ
api-version: 1.19
commands:
  voidfightz:
    description: teleports you to the VoidWorld
    usage: /<command>
  invulnerable:
    description: makes every1 invulnerable
    usage: /<command>