quests:
  kills:
    kill_quest1:
      name: Zombieslayer
      description: Kill 100 zombies.
      reward: Zombie spawn egg
      reward_amount: 1
      target:
        type: ZOMBIE
        count: 100
    kill_quest2:
      name: Skeletonslayer
      description: kill 36 skeletons.
      reward: Skeleton horse spawn egg
      reward_amount: 1
      target:
        type: SKELETON
        count: 1
