name: ChangeNameCommand
version: '1.0-SNAPSHOT'
main: me.in4.changenamecommand.ChangeNameCommand
api-version: 1.18
commands:
  newname:
    description: Change your name on this server.
    usage: /<command>
  resetname:
    description: resets your name.
    usage: /<command>
